# Generated by Django 4.2 on 2023-07-26 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_tasks_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projects',
            name='time_complete',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='todoapp.projects'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='time_complete',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
