# Generated by Django 4.2 on 2023-07-27 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_taskstemplate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TasksTemplate',
            new_name='TaskTemplate',
        ),
    ]
