# Generated by Django 4.2 on 2023-07-31 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_rename_taskstemplate_tasktemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
