# Generated by Django 4.2 on 2023-07-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_projects_user_tasks_user_tasktemplate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='user',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='user',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='user',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
